In [11]:
#Creating n dimenional arrays
import numpy as np
Array1= np.array([1,2,3], dtype= float, ndmin=2)
print(Array1)

[[1. 2. 3.]]


In [16]:
Array2= np.array([[1,2,3], [4,5,6]])
print(Array2)

[[1 2 3]
 [4 5 6]]


In [17]:
Array3= np.arange(10).reshape(2,5)
print(Array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
Array4= np.arange(3,15,3)
print(Array4)

[ 3  6  9 12]


In [34]:
Array5= np.random.randint(1,30,20).reshape(2,2,5)
print(Array5)

[[[ 2  2 16  7 23]
  [ 8 11 17  3  6]]

 [[16  9 11 17 20]
  [10 13 24 13 24]]]


In [29]:
Array5= np.ones((3,4), dtype=int)
print(Array5)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
Array5.flat

In [36]:
#Array Indexing
Array5= np.random.randint(1,30,20).reshape(2,2,5)
print(Array5)
Array5[1,1,4]

[[[10  3 28 13 10]
  [15  7 23 12  8]]

 [[ 8 12 14 17 23]
  [20 26  1  1  1]]]


1

In [51]:
#Converting list into array
Array1=np.array([12.23, 13.32, 100, 36.32], dtype='int')
print(Array1)

[ 12  13 100  36]


In [41]:
Array2=np.arange(2,11).reshape(3,3)
print(Array2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [42]:
Array3=np.zeros(10)
Array3[5]=11
print(Array3)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [49]:
#Reversing an array
Array4=np.arange(12,39)
print(Array4)
Array5=Array4[::-1]
print(Array5)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [50]:
#Converting datatype of array
Array4=np.arange(1,5, dtype='float')
print(Array4)

[1. 2. 3. 4.]


In [54]:
#2d array with 1 on the border and 0 inside.
Array1= np.ones(25, dtype='int').reshape(5,5)
Array1[1:-1,1:-1]=0
print(Array1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [56]:
help(np.pad)

Help on function pad in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
            Pads with the maximum value of all or part of

In [60]:
#Padding an existing array with 0 around the array
Array2=np.ones(16, dtype='int').reshape(4,4)
Array2=np.pad(Array2, pad_width=1, mode='constant', constant_values=0)
print(Array2)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


In [67]:
#Printing checkerboard pattern
Array1= np.ones(64, dtype='int').reshape(8,8)
Array1[::2, ::2]=0
Array1[1::2, 1::2]=0
print(Array1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [68]:
#Converting list and tuple into array
Arr1=np.array([1,2,3,4,5,6,7,8])
Arr2=np.array((5,6,7,8,9))
print(Arr1)
print(Arr2)

[1 2 3 4 5 6 7 8]
[5 6 7 8 9]
